#Bot's own user id for ignoring it in some cases.
botUserId: 607906445480034304
baseImagePath: images

#Twitch webhook api settings
twitchApi:
  address: 0.0.0.0
  port: 8080

#Role groups
roles:
  defaultMemberRole: 782242269834641409
  muteRole: 782242305306132540
  moderationRoles:
    - 782242591986155530
    - 782242378668310539
    - 782244241254252585

channels:
  botLog: 782242998767058944
  aybus: 782243045071781908
  sohbet: 782242136731942945

presenceUpdate:
  presenceUpdateFrequency: 5000
  statuses:
    - "Instagram: aybuse.uslu"
    - "Youtube: Aybusee"
    - "Twitter: aybuseuslu"

greeting:
  greetingDirectMessage: "**Aybuse**'nin Sunucusuna Hoşgeldin :tada:\n:small_orange_diamond: Hemen ***Kurallar*** kanalına bakmayı unutma,\n:small_orange_diamond: Eğer bir sorun olursa moderatörlere bildirebilirsin.\n\n**Aybuse'yi sosyal medyadan takip etmek için**\n:small_blue_diamond: İnstagram: *https://www.instagram.com/aybuse.uslu/*\n:small_blue_diamond: YouTube: *https://www.youtube.com/channel/UCercN6vdTVn07CadGL1Nesw*\n:small_blue_diamond: Twitter: *https://twitter.com/aybuseuslu*"
  greetingChannel: 782242976419282986
  greetingMessages:
    - Uyandığında <#386992275332399108> e 'Günaydın' demeyi unutma saat kaçta uyandığını merak ediyoruz.
    - Günün her saatinde sohbet odalarında boş yapılıyor, istersen bi' dene.
    - "Yayından bol bol clip alıp #clipler odasına atmayı unutma, sen de turuncu bir 'clipper' olabilirsin!"
    - Gacıysan 'huri' rolünü denemelisin!
    - Buyur kolonya <:golonya:691917008341565452> aman diyim bize corona bulaştırma.
    - Birlikte çıplak noel babaları popüler yapalım mı?
    - O da ne, uçan bir Çoti mi?
    - Aybusenin buffını gördün mü?
    - Kütahya'nın kireçli suyundan bi' bardak ister misin?

urlRestriction:
  warningMessage: "bu metin kanalında link paylaşımı yasaktır."
  restrictedChannels:
    - 782242136731942945

ticket:
  messageId: 782600181534687275
  reaction: 🎟️
  roleId: 782242338167849011

#Spam protection configurations
antiSpam:
  mute:
    threshold: 5
    maxDuplicates: 3
    message: "Spam yaptığın için %v dakika susturuldun. Bu davranışına devam edersen sunucudan atılabilirsin."
    channelMessage: "<@%v> spam sebebiyle %v dakika susturuldu."
    duration: 600000
  maxInterval: 2000
  maxDuplicatesInterval: 300000

loveMeter:
  texts:
    - Sizin aşkla alakanız yok hatta birbirinizden nefre ediyorsunuz.
    - Bence hiç zorlamayın.
    - Birbirinizin tipi değilsiniz.
    - Birbirinizi tanırsanız belki.
    - Az da olsa birbirinize karşı bişeyler hissediyorsunuz.
    - Bence uğraşırsanız bu iş olur.
    - Siz kesin birbirinizden hoşlanıyorsunuz.
    - Galiba birbirinizi seviyorsunuz.
    - Birbirinizi seviyorsunuz, bu aşk olmazsa dünya size küser.
    - BUNA AŞK DENİR!
    - SİZ BİRBİRİNİZE AŞIKSINIZ <3.

rockPaperScissors:
  defaultAvatar: discord.jpg
  hostWins: backgroundHostWins.png
  awayWins: backgroundAwayWins.png
  draw: backgroundDraw.png
